[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/locations/assets/*"
  to = "https://main-critical-worm.pgsdemo.com/locations/assets/:splat"
  status = 200
  force = true
  headers = {Host = "https://main-critical-worm.pgsdemo.com/" }

[[redirects]]
  from = "/*"
  to = "https://main-critical-worm.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://main-critical-worm.pgsdemo.com/" }