[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/financial-professionals/FP-0332/*"
  to = "https://right-solid-silkworm.sbx.pgsdemo.com/financial-professionals/FP-0332/:splat"
  status = 200
  force = true
  headers = {Host = "https://right-solid-silkworm.sbx.pgsdemo.com"}

[[redirects]]
  from = "/financial-professionals/*"
  to = "https://reputably-main-aphid.sbx.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://right-solid-silkworm.sbx.pgsdemo.com"}