[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/financial-professionals/fp-0132/*"
  to = "https://evenly-leading-mackerel.sbx.pgsdemo.com/financial-professionals/:splat"
  status = 200
  force = true
  headers = {Host = "https://evenly-leading-mackerel.sbx.pgsdemo.com/"}
  
[[redirects]]
  from = "/fp-0332/*"
  to = "https://right-solid-silkworm.sbx.pgsdemo.com/financial-professionals/:splat"
  status = 200
  force = true
  headers = {Host = "https://right-solid-silkworm.sbx.pgsdemo.com/"}

[[redirects]]
  from = "/*"
  to = "https://reputably-main-aphid.sbx.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://reputably-main-aphid.sbx.pgsdemo.com/"}