[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/locations/*"
  to = "https://main-critical-worm.pgsdemo.com/locations/:splat"
  status = 200
  force = true
  headers = {Host = "https://main-critical-worm.pgsdemo.com/", Access-Control-Allow-Origin = "*" }