[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/locations/*"
  to = "https://tensely-blank-kite.pgsdemo.com/:splat"
  status = 200
  force = true
